### ISSUE TITLE
12-hour locale but 24 hour used in time picker

### ISSUE THREAD

**Issue by jcachat** [DanielYKPan/date-time-picker#234]
My locale is using a 12 hour time format (so the input control is displaying am/pm as it should).  But the time picker is always using 24 hours.  Is there an option somewhere that I missed to change that to use a 12 hour format and allow changing an am/pm indicator?  Or can that be added so that it respects the locale?

**Comment by DanielYKPan** [comment]
No, the time picker currently would only be changed in 24 hours format.

**Comment by jcachat** [comment]
Understood but would you consider this as a feature request?  This will confuse my users and probably prevent me from using your library.

**Comment by DanielYKPan** [comment]
I have't found a way to implement this

**Comment by kyleabens** [comment]
I love this plugin so far but I agree...12 hour time format is a must have.

**Comment by DanielYKPan** [comment]
Thanks, @kyleabens 

The reason I have't implemented this is bc I couldn't find a way to detect if the user's locale is 12hour format or 24hour.

**Comment by kyleabens** [comment]
@DanielYKPan Instead of detecting the users locale couldn't it be a property of owl-date-time?  Something like [timeFormat]="'12'" [timeFormat]="'24'"?

**Comment by DanielYKPan** [comment]
Updated to the latest version

There is a property [hour12Timer] in owl-date-time, set it to true
```
[hour12Timer] = "true"
```

the timer would be in hour12 format mode

**Comment by jcachat** [comment]
That works great.  Thank you very much!

**Comment by kyleabens** [comment]
@DanielYKPan Works like a champ!  Thanks!

**Comment by sjPrajwal** [comment]
@DanielYKPan , picker accepting time in 24 hour format, but display 12 format in input field,  any way is there to change input display format to 24 hour format.

**Comment by Ritz52** [comment]
> @DanielYKPan , picker accepting time in 24 hour format, but display 12 format in input field, any way is there to change input display format to 24 hour format.

same problem

**Comment by Subham-Abhishek** [comment]
> @DanielYKPan, the picker accepts time in 24-hour format, but displays 12 hr formats in the input field, is there any way to change the input display format to 24-hour format?

the same problem any solution?

**Comment by bqback** [comment]
If anyone comes by looking for solutions for the above problem:

In the module with your date/time picker, in the `@NgModule` directive, make sure to [provide a locale](https://daniel-projects.firebaseapp.com/owlng/date-time-picker#localization), for example as follows:
```typescript
providers: [
    { provide: OWL_DATE_TIME_LOCALE, useValue: "whatever the appropriate locale for you is" },
]
```
or use a [custom datetime format](https://daniel-projects.firebaseapp.com/owlng/date-time-picker#implementation-format), for example as follows:
```typescript
providers: [
    { provide: OWL_DATE_TIME_FORMATS, useValue: yourCustomFormatObject },
]
```

You can even provide both, if you'd like, but be careful of what you're overriding! In my case, the problem was caused by using the correct locale, which was overridden with an incorrect formatting in `timePickerInput` provided among the custom formatting options.
