### ISSUE TITLE
Allow updating time through text input

### ISSUE THREAD

**Issue by hardikpthv** [DanielYKPan/date-time-picker#275]
It would be really helpful if one can be able to update time by typing in text box rather than ticking.

**Comment by sajuschi** [comment]
Hi DanielYKPan

If I change the locale to "de" I cannot change the time through through input-field, because I keep getting an owlDateTimeParseError whenever I change the time through the input field.
With locale set to english I don't get this error. 
I'm not entirely sure this belongs in this issue or is a new one, but because of this error I cannot use the input field and have to rely on the ticker (which can be annoying if I have to click 30 times to get 4:30).

Greetings,

sajuschi

**Comment by hardikpthv** [comment]
@DanielYKPan yes, I can do that. I meant if we add provision of having textbox right there, and can be set through [editableTime]. 
I will surely try to contribute for this. :)

**Comment by DanielYKPan** [comment]
Try the version 5.1.8
