### ISSUE TITLE
Range time 24 hours format

### ISSUE THREAD

**Issue by VladPavliuk** [DanielYKPan/date-time-picker#309]
Hello, I set property [hour12Timer]="false", but for range time it still 12 format type. Please can you tell, what I did wrong?

![screenshot from 2018-03-20 09-16-30](https://user-images.githubusercontent.com/24705251/37640699-7aff8322-2c1f-11e8-890c-2fa6fcfc49f0.png)

**Comment by DanielYKPan** [comment]
`[hour12Timer]` is used to set the timer mode. If you set it true, you could navigate the hour value from 0 to 23. You could see it on your picture.

What you asked for is to set the display value from the picker. You have to override the date-time format setting of the picker in order to show the 24hour format in your locale. You could learn more about this from [here](https://danielykpan.github.io/date-time-picker/#locale-formats).
