### ISSUE TITLE
 [pickerType]="'calendar'" and min date

### ISSUE THREAD

**Issue by OlgaMatosova** [DanielYKPan/date-time-picker#344]
if shoosing [pickerType]="'calendar'", min date doesn't work properly. if I set as min date 2018/02/03 for example, I can't check this day in datepicker

**Comment by DanielYKPan** [comment]
This is because you min date includes time value.
You have to set your min date like this
```
public minDate = new Date(2018, 1, 3) // minDate Feb 03, 2018
```

**Comment by OlgaMatosova** [comment]
Hi, no
I took example from documentation https://i.imgur.com/ZO5bOpv.png

while it work as date-time together (as on example) you can choose 12 February, but if you setup here  [pickerType]="'calendar'",  you will see as min date 12 February, but coudn't choose thia day

**Comment by DanielYKPan** [comment]
Yes. 
In the example, the min date have time value 10:30
```
// Min moment: February 12 2018, 10:30
    public min = new Date(2018, 1, 12, 10, 30);
```

As I said before, if you want to only to use 'calendar', you have to set your min date without any time value

```
// Min moment: February 12 2018
    public min = new Date(2018, 1, 12);
```

**Comment by OlgaMatosova** [comment]
Works, thank you.

**Comment by viktrus** [comment]
What if i want to set today as min date ( because i want min date as today which change everyday).

HTML:
 <input formControlName="departureDate" (focus)="dt3.open()" [owlDateTimeTrigger]="dt3 [min]="minDate" [owlDateTime]="dt3">
<owl-date-time [pickerType]="'calendar'" #dt3></owl-date-time>

component.ts
minDate = new Date(Date.now());

Thank you.
