### ISSUE TITLE
Format question

### ISSUE THREAD

**Issue by nico281** [DanielYKPan/date-time-picker#373]
Hi Daniel, how are you?
I'm writing you because i have a doubt about the date format. 
i need to dynamically change the output format like DD Month YYYY, Month DD YYYY, DD MM YYYY, MM DD YYYY. 
The thing is that i don't quite understand the documentation to format.
 It could be possible to you to give me a hand with this? i really appreciate it. 
Cheers!!

**Comment by DanielYKPan** [comment]
The doc has been well explained and there is demo to show how you can do that as well.

**Comment by infrarosso78** [comment]
I don't want to sound polemic but maybe if so many people are asking it is not really well explained in the documentation... at least on the one i manage to get my hand on.
If instead of answering always "go to the doc" you would have answered with the solution maybe other people would have find it and not keeping asking here. Don't you think?
