### ISSUE TITLE
Position in dropdown mode

### ISSUE THREAD

**Issue by DSCJeremy** [DanielYKPan/date-time-picker#44]
I'd like the ability to adjust the position of the dropdown mode.  it always opens underneath the control, and I don't necessarily want it to overflow to scrollbar.

**Comment by DanielYKPan** [comment]
@DSCJeremy 
So you want it to open above the control?

**Comment by DSCJeremy** [comment]
Not so much that, as the ability to choose the position.  I've figured out how to set it globally (css overried), but I don't want them all the same. For some of the controls, bottom looks best.  For some, top: -300 looks the best.  For others, I might like to swing it out to the right.  I just can't seem to have an option to set them individually.

**Comment by DanielYKPan** [comment]
@DSCJeremy 
I see what you mean. I would look at it in the next couple days.

**Comment by DanielYKPan** [comment]
@DSCJeremy 
Update to version 4.1.2 and it should be alright.

I added optional attribute 'position', the default value is 'bottom'. Other options could be 'top', 'left', 'right'.

**Comment by DSCJeremy** [comment]
thank you.  working great.

**Comment by johaven** [comment]
I can't use this option (v4.1.2):

Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'position' since it isn't a known property of 'input'. ("mm:ss'" [(dateTimePicker)]="searchService.Search.date.from" [theme]="'#ff6600'" [mode]="'dropdown'" [ERROR ->][position]="'right'" [hourTime]="'24'" [showSeconds]="true" readonly/>

**Comment by DanielYKPan** [comment]
@johaven 
I tested in a new angular quickstart download. It worked well.
You may have to try to debug yourself.
