### ISSUE TITLE
Datepicker not work for angular 7 SSR 

### ISSUE THREAD

**Issue by melayeromkar** [DanielYKPan/date-time-picker#552]
As mentioned on npm this datepicker is for angular 6+.Here 6+ means above angular 6.I am now using angular 7.1.1 and date picker version is -  

`  "ng-pick-datetime": "^7.0.0",
    "@angular/core": "^7.1.2",
`
**

 It gives the following problem after creating the build and running on node server-

**
```
/home/omkar/Workspace/Angular7/dist/server.js:258752
        __metadata("design:paramtypes", [Event]),
                                         ^

ReferenceError: Event is not defined

```

**Comment by pasevin** [comment]
Any news on this?

**Comment by morozeckiy** [comment]
same problem

**Comment by melayeromkar** [comment]
Still no updates and no solution....

**Comment by morozeckiy** [comment]
Solution => In server.ts
global[‘Event’]=null

**Comment by AakashPat** [comment]
> Solution => In server.ts
> global[‘Event’]=null

Could you please post that bit of code from your actual implementation?

**Comment by morozeckiy** [comment]
> > Solution => In server.ts
> > global[‘Event’]=null
> 
> Could you please post that bit of code from your actual implementation?

`// These are important and needed before anything else
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import {renderModuleFactory} from '@angular/platform-server';
import {enableProdMode} from '@angular/core';

import * as express from 'express';
import {join} from 'path';
import {readFileSync} from 'fs';

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// Express server
const app = express();
const domino = require('domino');
const PORT = 5200;
const DIST_FOLDER = join(process.cwd(), '');

// Our index.html we'll use as our template
const template = readFileSync(join(DIST_FOLDER, '', 'index.html')).toString();
const win = domino.createWindow(template);
global['window'] = win;
global['window'].requestAnimationFrame = {};
global['document'] = win.document;
global['Event'] = null;
global['KeyboardEvent'] = null;
global['Element'] = {};
global['Element'].prototype = {};
global['Element'].prototype.remove = undefined;

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const {AppServerModuleNgFactory, LAZY_MODULE_MAP} = require('./dist/server/main');

const {provideModuleMap} = require('@nguniversal/module-map-ngfactory-loader');

app.engine('html', (_, options, callback) => {
    renderModuleFactory(AppServerModuleNgFactory, {
        // Our index.html
        document: template,
        url: options.req.url,
        // DI so that we can get lazy-loading to work differently (since we need it to just instantly render it)
        extraProviders: [
            provideModuleMap(LAZY_MODULE_MAP)
        ]
    }).then(html => {
        callback(null, html);
    });
});

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, ''));

// Server static files from /browser
app.get('*.*', express.static(join(DIST_FOLDER, '')));

// All regular routes use the Universal engine
app.get('*', (req, res) => {
    res.render(join(DIST_FOLDER, '', 'index.html'), {req});
});

// Start up the Node server
app.listen(PORT, () => {
    console.log(`Node server listening on http://localhost:${PORT}`);
});
`

**Comment by pasevin** [comment]
Guys, try this out: https://github.com/DanielYKPan/date-time-picker/pull/577

**Comment by ThePatzen** [comment]
Any News about this?

**Comment by melayeromkar** [comment]
No....

*Thanks & Regards,*
*Omkar Jadhav*
Designation-Web Developer

**Comment by chirag-singhal** [comment]
Same Problem

**Comment by MuhammadSohailNazar** [comment]
i'm getting same issue as well
i'm using latest npm and angular CLI.

**"@angular/core": "^7.2.1",**
**"ng-pick-datetime": "^7.0.0"**

>E:\Angular\travesys-adminui\dist\server.js:413522
        __metadata("design:paramtypes", [Event]), 

anyone found anysolution?

**Comment by rajivkr** [comment]
Still facing the issue
