### ISSUE TITLE
Theme attribute isn't respected

### ISSUE THREAD

**Issue by Fadorico** [DanielYKPan/date-time-picker#58]
Setting [theme]="'[Hex code]'" doesn't seem to work at all. Even the "Choose Different Theme" demo https://danielykpan.github.io/date-time-picker/ doesn't work.

**Comment by DanielYKPan** [comment]
@Fadorico 
I tested it, and it worked well.

The demo not working because you might open the picker first and then set the theme colour. When you open the picker first time, it would set the theme colour as default.

In the Demo, you can try to set the theme colour before you open the picker first time. This is just in the demo.
In your apps, you don't have to. You just set  [theme]="'[Hex code]'"
