### ISSUE TITLE
Range datetime picker is allowing 1 input. I can't customize the preview for the 2nd custom input.

### ISSUE THREAD

**Issue by Napstergfr** [DanielYKPan/date-time-picker#696]
I think range DateTime picker should have a validation or a option for the 2nd value (end date) to preview in the UI.

**Comment by gongAll** [comment]
⛔ ⛔ ⛔    WARNING : READ BEFORE CREATING ISSUES    ⛔ ⛔ ⛔
This library was abandoned by its owner. I tried to contact him about 3 months ago with no success. Please cease to open new issues as they will not be handled by him. If you want, there is a [fork created by Daniel Moncada and his team](https://github.com/danielmoncada/date-time-picker) which is being currently maintained. Please don't open new issues here so that new users won't be mislead into believing this repo is still up-to-date.

**Comment by Napstergfr** [comment]
Thanks!
